### ISSUE TITLE
designing a part of an application or a general-purpose ?

### ISSUE THREAD

**Issue by chipbk10** [weeeBox/mobile-system-design#10]
Thanks for your efforts of writing these articles. I have been looking for these topics for a long time.
I noticed that the first question to clarify the requirement is always: "Are we designing a part of an application or a general-purpose ...?"

Why do we have to ask this question? What is the difference if the interviewer said "it's a part of an application" ?

**Comment by weeeBox** [comment]
Thank you! The main difference - a general-purpose library should be as flexible as possible to accommodate a wide range of use-cases. When you build a part of an app - you already know your limitations and can better optimize your design.

**Comment by weeeBox** [comment]
Another difference - you may want to avoid using a 3rd-party library while developing a library yourself. Any dependency may conflict with the host app and might pose licencing and privacy risks.

**Comment by chipbk10** [comment]
Good explanation. Thank you!
